### PR TITLE
Set player locale when creating Audience

### PR DESCRIPTION
**Pull request by CubBossa**
The pull request sets the client locale for Player audiences in the adventure-platform-bukkit module.
Until now, the client locale was only correct if the player changed their locale via settings while playing on the server.

### CODE REVIEW

**Comment by CubBossa** [comment]
So it is running fine on 1.12 up to 1.20.4, can't tell about 1.20.5 yet.
1.8 has been tested but does not work, it instead returns system language via `Locale.getDefault()`
Anything I can do to get this merged?

**Comment by zml2008** [comment]
Why do i feel like on 1.8 `getLocale()` was on `.spigot()` or something? is that just me making things up?

**Comment by zml2008** [comment]
oh yes, https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/browse/Bukkit-Patches/0018-Implement-Locale-Getter-for-Players.patch?at=e4d4710834f7b292bc496f41f1cf9ac363225c0e#21

Any chance you'd be able to revise this PR to include that variant? I'd love to spin off a -platform release soon including this PR.

**Comment by CubBossa** [comment]
`.spigot().getLocale()` doesn't seem to work properly either. In forums I read that for 1.8 you'd have to listen to the settings packet. The PR removed the event listening and replaced it with a direct `getLocale` call on the player object, but the event didn't even exist on 1.8 and has been introduced in 1.12 I think? So either way it'd be an improvement already but doesn't fix the 1.8 issues yet

At least, the following code did not work, it still returns `Locale.getDefault()`:
```Java
    private static final MethodHandle SPIGOT_SUPPORTED = findMethod(Player.class, "getLocale", findClass("org.bukkit.entity.Player.Spigot"));
    private static final MethodHandle SPIGOT_LOCALE_SUPPORTED = findMethod(findClass("org.bukkit.entity.Player.Spigot"), "getLocale", String.class);

//...

      builder.withDynamic(Identity.LOCALE, () -> {
        if (LOCALE_SUPPORTED != null) {
          try {
            return Translator.parseLocale((String) LOCALE_SUPPORTED.invoke(viewer));
          } catch (final Throwable error) {
            logError(error, "Failed to call getLocale() for %s", viewer);
          }
        }
        if (SPIGOT_SUPPORTED != null && SPIGOT_LOCALE_SUPPORTED != null) {
          try {
            final String localeStr = (String) SPIGOT_LOCALE_SUPPORTED.invoke(SPIGOT_SUPPORTED.invoke(viewer));
            return Translator.parseLocale(localeStr);
          } catch (final Throwable error) {
            logError(error, "Failed to call spigot().getLocale() for %s", viewer);
          }
        }
        return Locale.getDefault();
      });
```

**Comment by zml2008** [comment]
You know, if 1.8 is fixable then let's just let the 1.8 people PR that fix and get this release out already, otherwise the PR looks fine

**Review by zml2008 — APPROVED** [review]

**Pull request merged**
